import{NextResponse as e}
  from"next/server";import{getUserByEmail as r,createUser as t,updatePassword as s}
    from"../../../lib/db";import{hashPassword as o}
    from"../../../lib/auth";import{randomBytes as n}
    from"crypto";const a="sangtruong@gmail.com";export async function GET(i){const c=i.headers.get("x-seed-secret"),u=process.env.SEED_SECRET;if(!u)return e.json({error:"SEED_SECRET is not configured on the server"}
                                                                                                                                                                  ,{status:500}
                                                                                                                                                                  );if(!c||c!==u)return e.json({error:"Invalid secret. This endpoint can reset the Owner password, so it requires the x-seed-secret header."}
                                                                                                                                                                                               ,{status:401}
                                                                                                                                                                                               );const m="Tcm-"+n(4).toString("hex")+"!1",d=await o(m),w=await r(a);if(w)return"Owner"!==w.role?e.json({error:"An account with this email exists but is not an Owner; refusing to reset it."}
                                                                                                                                                                                                                                                                                                       ,{status:400}
                                                                                                                                                                                                                                                                                                       ):(await s(w.id,d),e.json({ok:!0,email:a,tempPassword:m,reset:!0}
                                                                                                                                                                                                                                                                                                                                 ));return await t({name:"Sang Truong",email:a,passwordHash:d,role:"Owner"}
                                                                                                                                                                                                                                                                                                                                                   )?e.json({ok:!0,email:a,tempPassword:m,reset:!1}
                                                                                                                                                                                                                                                                                                                                                            ):e.json({error:"Could not create owner account"}
                                                                                                                                                                                                                                                                                                                                                                     ,{status:500}
                                                                                                                                                                                                                                                                                                                                                                     )}
