export function makeViews2(ctx){const{n,p,y,m,g,f,b,w,$,S,L,k,x,M,v,t,a,i,d,o,r,e,c,u,h}
                                =ctx;
                                function j(e,t){async function a(){const e=await fetch("/api/users"),t=n.querySelector("#usersArea");if(!e.ok)return void(t&&(t.innerHTML='<div class="empty">Could not load users.</div>'));const a=void 0;s((await e.json()).data||[])}
                                                function s(e){const t=n.querySelector("#usersArea");if(!t)return;const l="Owner"===p.role;t.innerHTML=`<table>\n<thead><tr><th>Title</th><th>Name</th><th>Email</th><th>Added</th><th></th><th></th>${l?"<th></th><th></th>":""}
                                                </tr></thead>\n<tbody>${e.map(e=>`<tr>\n<td><select data-role-select="${e.id}
                                                ">${i.map(t=>`<option value="${d(t)}" ${e.role===t?"selected":""}
                                                >${d(t)}
                                                </option>`).join("")}
                                                </select></td>\n<td>${d(e.name)}
                                                </td>\n<td>${d(e.email)}
                                                </td>\n<td>${new Date(e.created_at).toLocaleDateString()}
                                                </td>\n<td><button class="btn secondary small" data-edit-name="${e.id}
                                                " data-current-name="${d(e.name)}
                                                ">Edit Name</button></td>\n<td><button class="btn secondary small" data-edit-email="${e.id}
                                                " data-current-email="${d(e.email)}
                                                ">Edit Email</button></td>\n${l?`<td><button class="btn secondary small" data-reset-pw="${e.id}
                                                " data-reset-name="${d(e.name)}
                                                ">Reset Password</button></td><td><button class="btn danger small" data-delete-user="${e.id}
                                                " data-delete-name="${d(e.name)}
                                                ">Delete</button></td>`:""}
                                                \n</tr>`).join("")||`<tr><td colspan="${l?8:6}
                                                " class="empty">No users yet</td></tr>`}
                                                </tbody>\n</table>`,t.querySelectorAll("[data-role-select]").forEach(e=>{e.addEventListener("change",async()=>{const t=parseInt(e.dataset.roleSelect,10),n=e.value,i=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"}
                                                                                                                                                                                                                                               ,body:JSON.stringify({id:t,role:n}
                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                 ),l=await i.json().catch(()=>({}
                                                                                                                                                                                                                                                               ));if(!i.ok)return alert(l.error||"Could not update position"),void a();s(l.data||[])}
                                                                                                                                            )}
                                                                                                                     ),t.querySelectorAll("[data-edit-name]").forEach(e=>{e.addEventListener("click",()=>{const t=parseInt(e.dataset.editName,10),a=(e.dataset.currentName||"").trim().split(/\s+/),n=void 0,i=void 0;L({title:"Edit Name",submitLabel:"Save",fields:[{key:"firstName",label:"First name",type:"text",default:a.length?a[0]:""}
                                                                                                                                                                                                                                                                                                                                                                      ,{key:"lastName",label:"Last name",type:"text",default:a.length>1?a.slice(1).join(" "):""}
                                                                                                                                                                                                                                                                                                                                                                      ],onSubmit:async e=>{const a=(e.firstName||"").trim(),n=(e.lastName||"").trim();if(!a||!n)return!1;const i=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,body:JSON.stringify({id:t,name:`${a}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${n}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ),l=await i.json().catch(()=>({}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ));return i.ok?(s(l.data||[]),!0):(alert(l.error||"Could not update name"),!1)}
                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                             )}
                                                                                                                                                                      ),t.querySelectorAll("[data-edit-email]").forEach(e=>{e.addEventListener("click",()=>{const t=parseInt(e.dataset.editEmail,10),c=e.dataset.currentEmail||"";L({title:"Edit Email",submitLabel:"Save",fields:[{key:"email",label:"Email",type:"text",default:c}
                                                                                                                                                                                                                                                                                                                                                                                   ],onSubmit:async e=>{const a=(e.email||"").trim();if(!a||!a.includes("@"))return!1;const i=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,body:JSON.stringify({id:t,email:a}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),l=await i.json().catch(()=>({}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ));return i.ok?(s(l.data||[]),!0):(alert(l.error||"Could not update email"),!1)}
                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                               )}
                                                                                                                                                                                                                        ),t.querySelectorAll("[data-delete-user]").forEach(e=>{e.addEventListener("click",async()=>{const t=parseInt(e.dataset.deleteUser,10),a=e.dataset.deleteName||"this user";if(!window.confirm(`Delete ${a}
                                                                                                                                                                                                                        ? This permanently removes their account and cannot be undone.`))return;const n=await fetch("/api/users",{method:"DELETE",headers:{"Content-Type":"application/json"}
                                                                                                                                                                                                                                                                                                                                  ,body:JSON.stringify({id:t}
                                                                                                                                                                                                                                                                                                                                                       )}
                                                                                                                                                                                                                                                                                                                    ),i=await n.json().catch(()=>({}
                                                                                                                                                                                                                                                                                                                                                  ));n.ok?s(i.data||[]):alert(i.error||"Could not delete user")}
                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                           ),t.querySelectorAll("[data-reset-pw]").forEach(e=>{e.addEventListener("click",async()=>{const t=parseInt(e.dataset.resetPw,10),a=e.dataset.resetName||"this user";if(!window.confirm(`Reset the password for ${a}
                                                                                                                                                                                                                                                                           ? This immediately invalidates their current password.`))return;const n=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"}
                                                                                                                                                                                                                                                                                                                                                                             ,body:JSON.stringify({id:t,resetPassword:!0}
                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                               ),i=await n.json().catch(()=>({}
                                                                                                                                                                                                                                                                                                                                                                                             ));n.ok?(s(i.data||[]),alert(`Password reset for ${a}
                                                                                                                                                                                                                                                                                                                                                                                             .\n\nTemporary password: ${i.tempPassword}
                                                                                                                                                                                                                                                                                                                                                                                             \n\nShare this with them directly — they'll sign in with it and should change it right away from the "Change password" button.`)):alert(i.error||"Could not reset password")}
                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                           )}
                                                t.innerHTML='<button class="btn" id="btnAddUser">+ Add User</button>',e.innerHTML='<p style="font-size:12.5px;color:var(--muted);margin:-4px 0 14px;">Staff accounts. New users get a temporary password to sign in with and change on their own.</p><div id="usersArea"><div class="empty">Loading users&hellip;</div></div>',n.querySelector("#btnAddUser").addEventListener("click",()=>{L({title:"Add User",submitLabel:"Create User",fields:[{key:"firstName",label:"First name",type:"text"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,{key:"lastName",label:"Last name",type:"text"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,{key:"email",label:"Email",type:"text"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,{key:"role",label:"Position",type:"select",default:i[0],options:i.map(e=>({value:e,label:e}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],onSubmit:async e=>{const t=(e.firstName||"").trim(),a=(e.lastName||"").trim();if(!t||!a||!e.email)return!1;const n=`${t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ${a}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   `,i=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ,body:JSON.stringify({name:n,email:e.email,role:e.role}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ),l=await i.json().catch(()=>({}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ));return i.ok?(s(l.data||[]),alert(`User created.\n\nTemporary password: ${l.tempPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \n\nShare this with ${n}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  directly — they'll sign in with it and should change it right away from the "Change password" button.`),!0):(alert(l.error||"Could not create user"),!1)}
                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                               ),a()}
                                function _(e,t){if(!t)return!0;const a=void 0;return[e.name,e.contact,e.referralSource,e.notes,...e.interests||[]].filter(Boolean).join(" | ").toLowerCase().includes(t)}
                                function H(e){return`<div class="panel crm-card"><h3>${d(e.name)}
                                </h3><div class="crm-row"><span class="crm-lbl">Contact</span>${d(e.contact)}
                                </div><div class="crm-row"><span class="crm-lbl">Orders</span>${e.orders}
                                </div><div class="crm-row"><span class="crm-lbl">Spend</span>$${e.spend.toLocaleString()}
                                </div><div class="crm-row"><span class="crm-lbl">Member since</span>${d(e.memberSince)}
                                </div><div class="crm-row" style="margin-top:8px;"><span class="crm-lbl" style="vertical-align:top;">Interests</span>${e.interests&&e.interests.length?`<span>${e.interests.map(e=>`<span class="tag low" style="margin:0 4px 4px 0;display:inline-block;">${d(e)}
                                </span>`).join("")}
                                </span>`:'<span style="color:var(--muted);font-style:italic;">No interest tags yet</span>'}
                                </div><div class="crm-row"><span class="crm-lbl">Referral</span><span style="${e.referralSource?"":"color:var(--muted);font-style:italic;"}
                                ">${e.referralSource?d(e.referralSource):"Not recorded"}
                                </span></div><div class="crm-row" style="margin-top:8px;"><span class="crm-lbl" style="vertical-align:top;">Wishlist</span><span style="${e.notes?"":"color:var(--muted);font-style:italic;"}
                                ">${e.notes?d(e.notes):"No wishlist notes yet — add via Shopify admin"}
                                </span></div></div>`}
                                function B(e){return e.map(H).join("")||'<div class="empty">No matching collectors</div>'}
                                function F(e,t){const a=e.collectors||[],n=(t||"").trim().toLowerCase(),s=a.filter(e=>_(e,n)),i=new Date,l=new Date(i.getFullYear(),i.getMonth(),i.getDate()),o=a.map(e=>{const t=e.memberSince?new Date(e.memberSince):null;if(!t||isNaN(t.getTime()))return null;let a=new Date(l.getFullYear(),t.getMonth(),t.getDate());a<l&&(a=new Date(l.getFullYear()+1,t.getMonth(),t.getDate()));const n=Math.round((a-l)/864e5),s=a.getFullYear()-t.getFullYear();return{name:e.name,contact:e.contact,daysAway:n,milestoneYears:s,dateLabel:a.toLocaleDateString("en-US",{month:"short",day:"numeric"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                          }
                                                                                                                                                                                                      ).filter(e=>e&&e.daysAway<=30).sort((e,t)=>e.daysAway-t.daysAway);return`<p style="font-size:12.5px;color:var(--muted);margin:-4px 0 14px;">Real recent customers pulled from Shopify — contact info, order history, Wishlist, Interests, and Referral source. Wishlist comes from the customer's Notes field in Shopify admin. Interests come from customer tags prefixed "interest-" (e.g. interest-pokemon) — type "interest-" in the Tags field on a customer's profile in Admin or POS and pick from the suggested list. Referral source comes from the "Referral Source" custom field on the customer. All three show up here on the next morning sync.</p>${o.length?`<div class="panel" style="border-left:3px solid var(--purple);"><h3>🎉 Upcoming Anniversaries (next 30 days)</h3><table><thead><tr><th>Collector</th><th>Anniversary</th><th>Milestone</th><th>Contact</th></tr></thead><tbody>${o.map(e=>`<tr><td>${d(e.name)}
                                                                                                                                                                                                      </td><td>${0===e.daysAway?"Today":1===e.daysAway?"Tomorrow":`${d(e.dateLabel)}
                                                                                                                                                                                                       (${e.daysAway}
                                                                                                                                                                                                       d)`}
                                                                                                                                                                                                       </td><td>${e.milestoneYears}
                                                                                                                                                                                                        year${1===e.milestoneYears?"":"s"}
                                                                                                                                                                                                        </td><td>${d(e.contact)}
                                                                                                                                                                                                        </td></tr>`).join("")}
                                                                                                                                                                                                        </tbody></table></div>`:""}
                                                                                                                                                                                                        <div class="panel" style="padding:12px 14px;margin-bottom:14px;"><input type="text" id="crmSearchInput" placeholder="Search by name, contact, interest, or referral source…" value="${d(t||"")}
                                                                                                                                                                                                        " style="width:100%;box-sizing:border-box;border:1px solid var(--border);border-radius:6px;padding:8px 12px;font-size:13px;font-family:inherit;"><div id="crmResultCount" style="font-size:12px;color:var(--muted);margin-top:6px;">${n?`Showing ${s.length.toLocaleString()}
                                                                                                                                                                                                         of ${a.length.toLocaleString()}
                                                                                                                                                                                                          collectors`:`${a.length.toLocaleString()}
                                                                                                                                                                                                           collector${1===a.length?"":"s"}
                                                                                                                                                                                                           `}
                                                                                                                                                                                                           </div></div><div class="crm-grid" id="crmGridContainer">${B(s)}
                                                                                                                                                                                                           </div>`}
                                function U(e,t){const a=t.collectors||[],n=e.querySelector("#crmSearchInput");if(!n)return;const s=n.value;n.focus(),n.setSelectionRange(s.length,s.length),n.addEventListener("input",()=>{m.crmSearch=n.value;const t=n.value.trim().toLowerCase(),s=a.filter(e=>_(e,t));e.querySelector("#crmGridContainer").innerHTML=B(s),e.querySelector("#crmResultCount").textContent=t?`Showing ${s.length.toLocaleString()}
                                 of ${a.length.toLocaleString()}
                                  collectors`:`${a.length.toLocaleString()}
                                   collector${1===a.length?"":"s"}
                                   `}
                                                                                                                                                                                                               )}
                                function R(e){const t=void 0;return`<p style="font-size:12.5px;color:var(--muted);margin:-4px 0 14px;">Computed each night from real Shopify order history — Gold Collector Tier (orders ≥ 30 and spend ≥ $7,500, lifetime) and Silver Collector Tier (orders ≥ 15 and spend ≥ $4,000, lifetime). These match the store's real Shopify customer segments (Gold/Silver Collector Tier) exactly. Customers who qualify for both are shown as Gold only.</p><div class="panel"><h3>Collector Rewards</h3><div class="tabs" style="display:flex;gap:8px;margin-bottom:10px;"><span class="tier-tab active" data-tier-filter="all" style="cursor:pointer;padding:4px 12px;border-radius:6px;background:var(--purple);color:#fff;font-weight:600;font-size:13px;">All</span><span class="tier-tab" data-tier-filter="Gold" style="cursor:pointer;padding:4px 12px;border-radius:6px;background:#eeeef5;color:var(--text);font-weight:600;font-size:13px;">Gold</span><span class="tier-tab" data-tier-filter="Silver" style="cursor:pointer;padding:4px 12px;border-radius:6px;background:#eeeef5;color:var(--text);font-weight:600;font-size:13px;">Silver</span></div><table><thead><tr><th>Customer</th><th>Tier</th><th>Orders</th><th>Spend</th><th>Contact</th></tr></thead><tbody>${(e.reward_customers||[]).map(e=>`<tr data-tier="${e.tier}"><td>${d(e.name)}
                                </td><td><span class="tier-pill tier-${e.tier}
                                ">${d(e.tier)}
                                </span></td><td>${e.orders}
                                </td><td>$${e.spend.toLocaleString()}
                                </td><td>${d(e.contact)}
                                </td></tr>`).join("")||'<tr><td colspan="5" class="empty">No customer data</td></tr>'}
                                </tbody></table></div><div class="panel"><h3>Policy</h3><p style="font-size:13px;color:var(--muted);">Silver Collector Tier: orders ≥ 15 and spend ≥ $4,000, both measured over the customer's lifetime. Gold Collector Tier: orders ≥ 30 and spend ≥ $7,500, both measured over the customer's lifetime. Source: computed nightly by matching the same lifetime thresholds as the store's real Shopify segments (Gold/Silver Collector Tier).</p></div>`}
                                function W(e){const t=e.staff_sales||[];if(!t.length)return'<div class="empty">No sales records visible for your role yet.</div>';const a=[...t].sort((e,t)=>t.sales-e.sales),n=Math.max(...a.map(e=>e.sales)),s=a.reduce((e,t)=>e+t.sales,0),i=a.reduce((e,t)=>e+t.transactions,0),l=a[0];return`<div class="kpi-grid"><div class="kpi"><div class="label">Total sales (period)</div><div class="value">$${s.toLocaleString()}
                                </div></div><div class="kpi"><div class="label">Total transactions</div><div class="value">${i}
                                </div></div><div class="kpi"><div class="label">Avg sale</div><div class="value">$${i?Math.round(s/i):0}
                                </div></div><div class="kpi"><div class="label">Top performer</div><div class="value" style="font-size:15px;">${d(l.name)}
                                </div><div class="delta up">$${l.sales.toLocaleString()}
                                </div></div></div><div class="panel"><h3>Sales</h3>${a.map((e,t)=>`<div class="bar-row"><div class="lbl" style="width:150px;">${0===t?"🥇 ":""}
                                ${d(e.name)}
                                </div><div class="bar-track"><div class="bar-fill" style="width:${Math.round(e.sales/n*100)}%"></div></div><div class="val" style="width:70px;">$${e.sales.toLocaleString()}</div><div class="val" style="width:90px;font-size:11.5px;color:var(--muted);">AOV $${e.transactions?Math.round(e.sales/e.transactions).toLocaleString():0}
                                </div></div>`).join("")}
                                </div>`}
                                function z(e){const t=e.collections_profit||[],a=t.filter(e=>"Sold"===e.status),n=t.filter(e=>"Sold"!==e.status),s=a.reduce((e,t)=>e+(t.saleTotal-t.purchasePrice),0),i=a.length?Math.round(a.reduce((e,t)=>e+(t.saleTotal-t.purchasePrice)/t.saleTotal*100,0)/a.length):0,l=a.length?Math.round(a.reduce((e,t)=>e+t.daysToSell,0)/a.length):0,o={}
                                  ;a.forEach(e=>{const t=o[e.category]=o[e.category]||{purchase:0,sale:0,count:0}
                                                 ;t.purchase+=e.purchasePrice,t.sale+=e.saleTotal,t.count+=1}
                                             );const r=Object.entries(o).map(([e,t])=>({cat:e,profit:t.sale-t.purchase,marginPct:Math.round((t.sale-t.purchase)/t.sale*100),count:t.count}
                                                                                       )).sort((e,t)=>t.marginPct-e.marginPct),c=r[0];return`<div class="kpi-grid"><div class="kpi"><div class="label">Total realized profit</div><div class="value">$${s.toLocaleString()}
                                                                                       </div><div class="delta">${a.length}
                                                                                        collections sold</div></div><div class="kpi"><div class="label">Avg margin (sold)</div><div class="value">${i}
                                                                                        %</div></div><div class="kpi"><div class="label">Avg days to sell</div><div class="value">${l}
                                                                                        d</div></div><div class="kpi"><div class="label">In processing</div><div class="value">${n.length}
                                                                                        </div><div class="delta">not yet sold</div></div><div class="kpi"><div class="label">Best category by margin</div><div class="value" style="font-size:16px;">${c?d(c.cat):"—"}
                                                                                        </div><div class="delta up">${c?c.marginPct+"% margin":""}
                                                                                        </div></div></div><div class="panel"><h3>Margin by category</h3><table><thead><tr><th>Category</th><th>Collections sold</th><th>Total profit</th><th>Margin</th></tr></thead><tbody>${r.map(e=>`<tr><td>${d(e.cat)}
                                                                                        </td><td>${e.count}
                                                                                        </td><td>$${e.profit.toLocaleString()}
                                                                                        </td><td><span class="tag ${e.marginPct>=40?"low":e.marginPct>=25?"med":"high"}
                                                                                        ">${e.marginPct}
                                                                                        %</span></td></tr>`).join("")||'<tr><td colspan="4" class="empty">No sold collections yet</td></tr>'}
                                                                                        </tbody></table></div><div class="panel"><h3>Every collection, purchase to sale</h3><table><thead><tr><th>Collection</th><th>Category</th><th>Purchase</th><th>Sale</th><th>Profit</th><th>Margin</th><th>Days to sell</th><th>Status</th><th></th></tr></thead><tbody>${t.map((e,idx)=>{const t="Sold"===e.status,a=t?e.saleTotal-e.purchasePrice:null,n=t?Math.round(a/e.saleTotal*100):null;return`<tr><td>${d(e.name)}
                                                                                        </td><td>${d(e.category)}
                                                                                        </td><td>$${e.purchasePrice.toLocaleString()}
                                                                                        </td><td>${t?"$"+e.saleTotal.toLocaleString():"—"}
                                                                                        </td><td>${t?"$"+a.toLocaleString():"—"}
                                                                                        </td><td>${t?`<span class="tag ${n>=40?"low":n>=25?"med":"high"}
                                                                                        ">${n}
                                                                                        %</span>`:"—"}
                                                                                        </td><td>${t?e.daysToSell+"d":"—"}
                                                                                        </td><td><span class="status-pill ${t?"status-Completed":"status-Preparing"}
                                                                                        ">${d(e.status)}
                                                                                        </span></td><td><button class="btn danger small" data-del-collection="${idx}">Delete</button></td></tr>`}
                                                                                                                                                                                                                                                                                                                                                              ).join("")}
                                                                                                                                                                                                                                                                                                                                                              </tbody></table></div>`}
                                function G(dat){const projects=dat.projects||[];if(!projects.length)return '<div class="empty">No projects yet — nothing real to pull this from, so it\'s been left empty rather than showing made-up ones.</div>';const statusClassMap={Planning:"med","In Progress":"low","On Hold":"high",Done:"low"}
                                                ;return `<div class="projects-grid">${projects.map(proj=>{const msDone=(proj.milestones||[]).filter(ms=>ms.done).length,msTotal=(proj.milestones||[]).length;return `<div class="panel project-card"><h3>${d(proj.name)}
                                                 <span class="tag ${statusClassMap[proj.status]||"low"}
                                                 ">${d(proj.status)}
                                                 </span></h3><div class="project-owner">Owner: <b>${d(proj.owner)}
                                                 </b></div><div class="progress-track" style="width:100%;margin:8px 0;"><div class="progress-fill" style="width:${msTotal?Math.round(msDone/msTotal*100):0}
                                                 %"></div></div><div class="project-section-lbl">Milestones (${msDone}
                                                 /${msTotal}
                                                 )</div>${(proj.milestones||[]).map(ms=>`<div class="checklist-row" data-toggle-milestone="${ms.id}
                                                 " data-project-id="${proj.id}
                                                 "><span class="checkbox ${ms.done?"checked":""}
                                                 "></span>${d(ms.title)}
                                                 </div>`).join("")}
                                                 <div class="checklist-row" data-add-milestone="${proj.id}
                                                 " style="color:var(--purple-dark);font-weight:600;">+ Add milestone</div><div class="project-section-lbl">Tasks</div>${(proj.tasks||[]).map(tk=>`<div class="checklist-row" data-toggle-task="${tk.id}
                                                 " data-project-id="${proj.id}
                                                 "><span class="checkbox ${tk.done?"checked":""}
                                                 "></span>${d(tk.title)}
                                                 </div>`).join("")}
                                                 <div class="checklist-row" data-add-task="${proj.id}
                                                 " style="color:var(--purple-dark);font-weight:600;">+ Add task</div></div>`}
                                                                                                   ).join("")}
                                                                                                   </div><p style="font-size:12.5px;color:var(--muted);margin-top:4px;">Everyone can see all projects; only the project owner (or the Operations Manager) can check items off.</p>`}
                                function J(){n.querySelectorAll("[data-toggle-milestone]").forEach(el=>{el.addEventListener("click",async()=>{const projectId=parseInt(el.dataset.projectId,10),itemId=parseInt(el.dataset.toggleMilestone,10),upd=await S("toggleProjectMilestone",{projectId,itemId}
                                                                                                                                                                                                                                                           );upd&&(m.data.projects=upd,M())}
                                                                                                                            )}
                                                                                                   ),n.querySelectorAll("[data-toggle-task]").forEach(el=>{el.addEventListener("click",async()=>{const projectId=parseInt(el.dataset.projectId,10),itemId=parseInt(el.dataset.toggleTask,10),upd=await S("toggleProjectTask",{projectId,itemId}
                                                                                                                                                                                                                                                                                                         );upd&&(m.data.projects=upd,M())}
                                                                                                                                                                               )}
                                                                                                                                                      ),n.querySelectorAll("[data-add-milestone]").forEach(el=>{el.addEventListener("click",()=>{const projectId=parseInt(el.dataset.addMilestone,10);L({title:"Add Milestone",submitLabel:"Add",fields:[{key:"title",label:"Milestone title",type:"text"}
                                                                                                                                                                                                                                                                                                                                                         ],onSubmit:async v=>{if(!v.title)return!1;const upd=await S("addProjectMilestone",{projectId,title:v.title}
                                                                                                                                                                                                                                                                                                                                                                                                                     );return!!upd&&(m.data.projects=upd,M(),!0)}
                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                           ),n.querySelectorAll("[data-add-task]").forEach(el=>{el.addEventListener("click",()=>{const projectId=parseInt(el.dataset.addTask,10);L({title:"Add Task",submitLabel:"Add",fields:[{key:"title",label:"Task title",type:"text"}
                                                                                                                                                                                                                                                                                                                                                                                               ],onSubmit:async v=>{if(!v.title)return!1;const upd=await S("addProjectTask",{projectId,title:v.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                           );return!!upd&&(m.data.projects=upd,M(),!0)}
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                   )}
                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                           )}
                                function K(actionsEl){actionsEl.innerHTML='<button class="btn" id="btnAddProject">+ New Project</button>',n.querySelector("#btnAddProject").addEventListener("click",()=>{const fields=[{key:"name",label:"Project name",type:"text"}
                                                                                                                                                                                                                        ,{key:"status",label:"Status",type:"select",default:"Planning",options:["Planning","In Progress","On Hold","Done"].map(st=>({value:st,label:st}
                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                        ];["Owner","Operations Manager"].includes(p.role)&&fields.push({key:"owner",label:"Owner",type:"select",default:p.role,options:i.map(rl=>({value:rl,label:rl}
                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                    ),L({title:"New Project",submitLabel:"Create Project",fields,onSubmit:async v=>{if(!v.name)return!1;const upd=await S("addProject",v);return!!upd&&(m.data.projects=upd,M(),!0)}
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                           )}
                                                                                                                                                                                             )}
                                function Q(dat){const sprints=dat.sprints||[];if(!sprints.length)return '<div class="empty">No sprint visible for your role yet.</div>';return `<div class="goals-grid">${sprints.map(sp=>{const done=(sp.goals||[]).filter(g=>g.done).length,total=(sp.goals||[]).length;return `<div class="panel goal-card"><h3>${d(sp.role)}
                                 <span class="goal-maps">${d(sp.sprintLabel)}
                                 </span></h3><div class="progress-track" style="width:100%;margin-bottom:10px;"><div class="progress-fill" style="width:${total?Math.round(done/total*100):0}
                                 %"></div></div>${(sp.goals||[]).map(gl=>`<div class="checklist-row" data-toggle-goal="${gl.id}
                                 " data-sprint-id="${sp.id}
                                 "><span class="checkbox ${gl.done?"checked":""}
                                 "></span>${d(gl.text)}
                                 </div>`).join("")}
                                 <div class="checklist-row" data-add-goal="${sp.id}
                                 " style="color:var(--purple-dark);font-weight:600;">+ Add goal</div></div>`}
                                                                                                                                                                                                                      ).join("")}
                                                                                                                                                                                                                      </div>`}
                                function V(){n.querySelectorAll("[data-toggle-goal]").forEach(el=>{el.addEventListener("click",async()=>{const sprintId=parseInt(el.dataset.sprintId,10),goalId=parseInt(el.dataset.toggleGoal,10),upd=await S("toggleSprintGoal",{sprintId,goalId}
                                                                                                                                                                                                                                               );upd&&(m.data.sprints=upd,M())}
                                                                                                                       )}
                                                                                              ),n.querySelectorAll("[data-add-goal]").forEach(el=>{el.addEventListener("click",()=>{const sprintId=parseInt(el.dataset.addGoal,10);L({title:"Add Sprint Goal",submitLabel:"Add",fields:[{key:"text",label:"Goal",type:"text"}
                                                                                                                                                                                                                                                                                        ],onSubmit:async v=>{if(!v.text)return!1;const upd=await S("addSprintGoal",{sprintId,text:v.text}
                                                                                                                                                                                                                                                                                                                                                   );return!!upd&&(m.data.sprints=upd,M(),!0)}
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                     )}
                                                                                                                                                                       )}
                                                                                                                                              )}
                                function X(actionsEl){actionsEl.innerHTML='<button class="btn" id="btnAddSprint">+ New Sprint</button>',n.querySelector("#btnAddSprint").addEventListener("click",()=>{const fields=[{key:"sprintLabel",label:"Sprint label (e.g. Sprint 12: Jul 28 – Aug 8)",type:"text"}
                                                                                                                                                                                                                     ];["Owner","Operations Manager"].includes(p.role)&&fields.push({key:"role",label:"Role",type:"select",default:p.role,options:i.map(rl=>({value:rl,label:rl}
                                                                                                                                                                                                                                                                                                                                                             ))}
                                                                                                                                                                                                                                                                                    ),L({title:"New Sprint",submitLabel:"Create Sprint",fields,onSubmit:async v=>{if(!v.sprintLabel)return!1;const upd=await S("addSprint",v);return!!upd&&(m.data.sprints=upd,M(),!0)}
                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                          )}
                                function Y(dat){const goalRoles=dat.goal_roles||[];return `<div class="goals-grid">${goalRoles.map(rr=>`<div class="panel goal-card"><h3>${d(rr.role)}
                                 <span class="goal-maps">${d(rr.maps)}
                                 </span></h3>${rr.kpis.map(kp=>{const better=kp.lowerIsBetter?kp.current<=kp.target:kp.current>=kp.target,pct=kp.lowerIsBetter?Math.min(100,Math.round(kp.target/Math.max(kp.current,.001)*100)):Math.min(100,Math.round(kp.current/Math.max(kp.target,.001)*100));return `<div class="kpi-row"><div class="kpi-row-top"><span>${d(kp.name)}
                                 </span><span class="kpi-vals">${kp.current}
                                 ${kp.unit}
                                  <span class="arrow">&rarr;</span> ${kp.target}
                                  ${kp.unit}
                                  </span></div><div class="progress-track" style="width:100%;"><div class="progress-fill ${better?"":"warn"}
                                  " style="width:${pct}
                                  %"></div></div></div>`}
                                                           ).join("")}
                                                           </div>`).join("")}
                                                           </div>`}
                                function rankChart(items,title){const ranked=items.filter(i=>i.sales30d!=null&&i.sales30d>0).slice().sort((a,b)=>b.sales30d-a.sales30d);if(!ranked.length)return "";const max=ranked[0].sales30d||1;return `<div class="panel"><h3>${d(title)}</h3>${ranked.map(i=>`<div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:12.5px;margin-bottom:3px;"><span>${d(i.category)}</span><span style="color:var(--muted);">$${i.sales30d.toLocaleString()}</span></div><div class="progress-track" style="width:100%;"><div class="progress-fill" style="width:${Math.max(2,Math.round(i.sales30d/max*100))}%;background:var(--purple);"></div></div></div>`).join("")}</div>`}
function sparkline(monthly){if(!monthly||!monthly.length)return '<span style="color:var(--muted);">—</span>';const max=Math.max(1,...monthly.map(m=>m.sales||0));return `<div style="display:flex;align-items:flex-end;gap:3px;height:30px;">${monthly.map(m=>`<div title="${d(m.month)}: $${(m.sales||0).toLocaleString()}" style="width:11px;height:${Math.max(2,Math.round((m.sales||0)/max*26))}px;background:var(--purple);border-radius:2px 2px 0 0;"></div>`).join("")}</div>`}
function momDelta(monthly){if(!monthly||monthly.length<2)return '<span style="color:var(--muted);">—</span>';const prev=monthly[monthly.length-2].sales||0,curr=monthly[monthly.length-1].sales||0;if(prev===0&&curr===0)return '<span style="color:var(--muted);">—</span>';if(prev===0)return '<span style="color:var(--green);font-weight:600;">New</span>';const pct=Math.round((curr-prev)/prev*1000)/10,up=pct>=0;return `<span style="color:${up?"var(--green)":"var(--red)"};font-weight:600;">${up?"▲":"▼"} ${Math.abs(pct)}%</span>`}
function trendRow(i){return `<tr><td>${d(i.category)}</td><td>${null!=i.inStock?i.inStock.toLocaleString():"—"}</td><td>${null!=i.sales30d?"$"+i.sales30d.toLocaleString():"—"}</td><td>${sparkline(i.monthly)}</td><td>${momDelta(i.monthly)}</td></tr>`}
function rC(dat){const items=dat.comics_items||[];const totalInStock=items.reduce((a,i)=>a+(i.inStock||0),0);const monthLabels=(items.find(i=>i.monthly&&i.monthly.length)||{}).monthly||[];return `<p style="font-size:12.5px;color:var(--muted);margin:-4px 0 14px;">Real category rollup pulled from the store's Shopify collections — this catalog is too large (80,000+ comics alone) to list item by item, so this shows counts and 30-day sales by category/vendor instead.</p><div class="kpi-grid"><div class="kpi"><div class="label">Total in-stock (categories below)</div><div class="value">${totalInStock.toLocaleString()}</div></div></div>${rankChart(items,"Ranked by 30-day sales")}<div class="panel"><h3>Comics categories</h3><table><thead><tr><th>Category</th><th>In stock</th><th>Sales (30d)</th><th>Trend (${monthLabels.map(m=>d(m.month)).join(" → ")})</th><th>MoM Δ</th></tr></thead><tbody>${items.map(i=>trendRow(i)).join("")||'<tr><td colspan="5" class="empty">No data</td></tr>'}</tbody></table></div>`}
function rT(dat){const items=dat.tcg_items||[];const monthLabels=(items.find(i=>i.monthly&&i.monthly.length)||{}).monthly||[];return `<p style="font-size:12.5px;color:var(--muted);margin:-4px 0 14px;">Real category rollup pulled from Shopify. No dedicated "Pokemon" collection exists in this store's setup, so that row shows sales only (no in-stock count without paging the full catalog).</p>${rankChart(items,"Ranked by 30-day sales")}<div class="panel"><h3>Cards & games categories</h3><table><thead><tr><th>Category</th><th>In stock</th><th>Sales (30d)</th><th>Trend (${monthLabels.map(m=>d(m.month)).join(" → ")})</th><th>MoM Δ</th></tr></thead><tbody>${items.map(i=>trendRow(i)).join("")||'<tr><td colspan="5" class="empty">No data</td></tr>'}</tbody></table></div>`}
function rA(dat){const automations=dat.automations||[];return `<div class="panel"><h3>Active rules</h3>${automations.map(a=>`<div class="automation-row"><div class="switch ${a.enabled?"on":""}
                                " data-id="${a.id}
                                "><div class="knob"></div></div><div class="flow"><b>When</b> ${d(a.trigger)}
                                 <span class="arrow">&rarr;</span> <b>then</b> ${d(a.action)}
                                 </div><div class="run-count">${a.runs}
                                  runs</div></div>`).join("")||'<div class="empty">No automations configured yet.</div>'}
                                  </div>`}
                                function wA(){n.querySelectorAll(".switch").forEach(el=>{el.addEventListener("click",async()=>{if(!["Owner","Operations Manager"].includes(p.role))return;const id=parseInt(el.dataset.id,10),upd=await S("toggleAutomation",{id}
                                                                                                                                                                                                                                          );upd&&(m.data.automations=upd,M())}
                                                                                                             )}
                                                                                    )}

return{j,_,H,B,F,U,R,W,z,G,J,K,Q,V,X,Y,rC,rT,rA,wA}
                                ;}
