export function makeViews1(ctx){const{n,p,y,m,g,f,b,w,$,S,L,k,x,M,v,t,a,i,d,o,r,e,c,u,h}
                                =ctx;
                                function C(e,t){const a=t.chat_channels||[];null==m.activeChannelId&&a.length&&(m.activeChannelId=a[0].id);const n=a.find(e=>e.id===m.activeChannelId)||a[0],s=["Owner","Operations Manager"].includes(p.role);e.innerHTML=`<div class="chat-layout">\n<div class="chat-channels">\n${a.map(e=>`<div class="chat-channel-item ${n&&e.id===n.id?"active":""}
                                " data-channel-id="${e.id}
                                "><span class="chat-channel-name">#${d(e.name)}
                                <span class="chat-channel-desc">${d(e.description)}
                                </span></span>${s?`<span class="chat-channel-actions"><a href="#" data-edit-channel="${e.id}
                                " title="Edit channel">✎</a><a href="#" data-delete-channel="${e.id}
                                " title="Delete channel">✕</a></span>`:""}
                                </div>`).join("")}
                                \n${s?'<div class="chat-channel-item" id="btnAddChannel" style="color:var(--purple-dark);font-weight:600;">+ Add channel</div>':""}
                                \n${a.length?"":'<div class="empty">No channels yet</div>'}
                                \n</div>\n<div class="chat-main">\n<div class="chat-messages" id="chatMessages"><div class="empty">Loading messages…</div></div>\n<button class="chat-scroll-bottom" id="chatScrollBottom" style="display:none;" type="button">&darr; New messages</button>\n<div class="chat-composer">\n<input type="file" id="chatImageInput" accept="image/*" style="display:none;">\n<button class="btn secondary small" id="chatAttach" title="Attach an image" type="button">📎</button>\n<input type="text" id="chatInput" placeholder="${n?"Message #"+n.name:""}
                                ">\n<button class="btn small" id="chatSend">Send</button>\n</div>\n</div>\n</div>`,e.querySelectorAll(".chat-channel-item[data-channel-id]").forEach(a=>{a.addEventListener("click",v=>{v.target.closest("[data-edit-channel],[data-delete-channel]")||(m.activeChannelId=parseInt(a.dataset.channelId,10),x(),C(e,t))}
                                                                                                                                                                                                            )}
                                                                                                                                                                                     ),e.querySelectorAll("[data-edit-channel]").forEach(a=>{a.addEventListener("click",async v=>{v.preventDefault(),v.stopPropagation();const c=parseInt(a.dataset.editChannel,10),h=(t.chat_channels||[]).find(e=>e.id===c);h&&L({title:"Edit Channel",submitLabel:"Save",fields:[{key:"name",label:"Channel name",type:"text",default:h.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ,{key:"description",label:"Description",type:"text",default:h.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],onSubmit:async v=>{if(!v.name)return!1;const g=await S("editChatChannel",{id:c,name:v.name,description:v.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             );return!!g&&(m.data.chat_channels=g,C(e,t),!0)}
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                   )}
                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                         ),e.querySelectorAll("[data-delete-channel]").forEach(a=>{a.addEventListener("click",async v=>{if(v.preventDefault(),v.stopPropagation(),!window.confirm("Delete this channel? All its messages will be deleted too. This can't be undone."))return;const c=parseInt(a.dataset.deleteChannel,10),h=await S("deleteChatChannel",{id:c}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );h&&(m.data.chat_channels=h,m.activeChannelId===c&&(m.activeChannelId=h.length?h[0].id:null),x(),C(e,t))}
                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                               ),e.querySelector("#btnAddChannel")?.addEventListener("click",()=>{L({title:"Add Chat Channel",submitLabel:"Create",fields:[{key:"name",label:"Channel name",type:"text"}
                                                                                                                                                                                                                                                                                                                                                                                                                           ,{key:"description",label:"Description",type:"text"}
                                                                                                                                                                                                                                                                                                                                                                                                                           ],onSubmit:async e=>{if(!e.name)return!1;const t=await S("addChatChannel",e);return!!t&&(m.data.chat_channels=t,m.activeChannelId=t[t.length-1].id,M(),!0)}
                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                     );let i=0;async function l(t){if(!n)return;const a=await fetch(`/api/chat/messages?channelId=${n.id}
                                                                                                                                                                                                                                                                                                                                                     `);if(!a.ok)return;const s=void 0,o=(await a.json()).data||[],c=e.querySelector("#chatMessages"),v=e.querySelector("#chatScrollBottom");if(!c)return;const u=c.scrollHeight-c.scrollTop-c.clientHeight<80;c.innerHTML=o.length?o.map(e=>{const t=void 0,a=(e.authorEmail?e.authorEmail===p.email:e.author===p.name)||["Owner","Operations Manager"].includes(p.role);return`<div class="chat-msg" data-message-id="${e.id}
                                                                                                                                                                                                                                                                                                                                                     ">\n<span class="chat-msg-author">${d(e.author)}
                                                                                                                                                                                                                                                                                                                                                     </span><span class="chat-msg-ts">${d(e.ts)}
                                                                                                                                                                                                                                                                                                                                                     ${e.editedAt?" (edited)":""}
                                                                                                                                                                                                                                                                                                                                                     </span>\n${a?`<span class="chat-msg-actions"><a href="#" data-edit-msg="${e.id}
                                                                                                                                                                                                                                                                                                                                                     ">Edit</a><a href="#" data-delete-msg="${e.id}
                                                                                                                                                                                                                                                                                                                                                     ">Delete</a></span>`:""}
                                                                                                                                                                                                                                                                                                                                                     \n<div class="chat-msg-body">${e.body?r(e.body):""}
                                                                                                                                                                                                                                                                                                                                                     ${e.imageUrl?`<div style="margin-top:6px;"><img src="${e.imageUrl}
                                                                                                                                                                                                                                                                                                                                                     " style="max-width:280px;max-height:280px;border-radius:8px;display:block;"></div>`:""}
                                                                                                                                                                                                                                                                                                                                                     </div>\n</div>`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ).join(""):'<div class="empty">No messages yet — say something.</div>';const h=void 0;t||u||0===i?(c.scrollTop=c.scrollHeight,v&&(v.style.display="none")):o.length>i&&v&&(v.style.display="block"),i=o.length,c.querySelectorAll("[data-edit-msg]").forEach(e=>{e.addEventListener("click",t=>{t.preventDefault();const a=parseInt(e.dataset.editMsg,10),s=o.find(e=>e.id===a);s&&L({title:"Edit Message",submitLabel:"Save",fields:[{key:"body",label:"Message",type:"textarea",default:s.body}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],onSubmit:async e=>{if(!e.body||!e.body.trim())return!1;const t=void 0;return!!await S("editChatMessage",{channelId:n.id,messageId:a,body:e.body}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )&&(l(!1),!0)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ),c.querySelectorAll("[data-delete-msg]").forEach(e=>{e.addEventListener("click",async t=>{t.preventDefault();const a=parseInt(e.dataset.deleteMsg,10);if(!window.confirm("Delete this message? This can't be undone."))return;const s=void 0;await S("deleteChatMessage",{channelId:n.id,messageId:a}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )&&l(!1)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )}
                                                async function o(t){const a=e.querySelector("#chatInput"),s=a.value.trim();if(!s&&!t||!n)return;a.value="";const i=void 0;await S("postChatMessage",{channelId:n.id,body:s,imageData:t||void 0}
                                                                                                                                                                                  )&&l(!0)}
                                                e.querySelector("#chatScrollBottom")?.addEventListener("click",()=>{const t=e.querySelector("#chatMessages"),a=e.querySelector("#chatScrollBottom");t&&(t.scrollTop=t.scrollHeight),a&&(a.style.display="none")}
                                                                                                       ),e.querySelector("#chatMessages")?.addEventListener("scroll",()=>{const t=e.querySelector("#chatMessages"),a=e.querySelector("#chatScrollBottom");t&&a&&t.scrollHeight-t.scrollTop-t.clientHeight<40&&(a.style.display="none")}
                                                                                                                                                            ),e.querySelector("#chatSend")?.addEventListener("click",()=>o()),e.querySelector("#chatInput")?.addEventListener("keydown",t=>{"Enter"===t.key&&e.querySelector("#chatSend").click()}
                                                                                                                                                                                                                                                                              ),e.querySelector("#chatAttach")?.addEventListener("click",()=>{e.querySelector("#chatImageInput").click()}
                                                                                                                                                                                                                                                                                                                                 ),e.querySelector("#chatImageInput")?.addEventListener("change",e=>{const t=e.target.files&&e.target.files[0];if(!t)return;if(t.size>2e6)return alert("Image is too large — 2MB max."),void(e.target.value="");const a=new FileReader;a.onload=()=>{o(a.result),e.target.value=""}
                                                                                                                                                                                                                                                                                                                                                                                                     ,a.readAsDataURL(t)}
                                                                                                                                                                                                                                                                                                                                                                                        ),l(!0),x(),m.chatPollInterval=setInterval(()=>l(!1),5e3)}
                                function E(e,t,a){const n=a.docs||[];T(t),n.length?D(e,a):e.innerHTML='<div class="empty">No docs yet — add the first one to start building the wiki.</div>'}
                                function T(e){e.innerHTML='<button class="btn" id="btnAddDoc">+ New Doc</button>',n.querySelector("#btnAddDoc").addEventListener("click",()=>{L({title:"New Doc",submitLabel:"Create",fields:[{key:"cat",label:"Category",type:"text",default:"General"}
                                                                                                                                                                                                                              ,{key:"title",label:"Title",type:"text"}
                                                                                                                                                                                                                              ,{key:"docBody",label:"Body",type:"textarea"}
                                                                                                                                                                                                                              ,{key:"pinned",label:"Pin to top of Docs & Wiki (e.g. company policies)",type:"checkbox"}
                                                                                                                                                                                                                              ,{key:"attachmentData",label:"Attach a file (optional, 20MB max)",type:"file"}
                                                                                                                                                                                                                              ],onSubmit:async e=>{if(!e.title||!e.docBody&&!e.attachmentData)return!1;const t=await S("addDoc",{cat:e.cat,title:e.title,docBody:e.docBody||"",pinned:e.pinned,attachmentData:e.attachmentData,attachmentName:e.attachmentDataName}
                                                                                                                                                                                                                                                                                                                       );return!!t&&(m.data.docs=t,m.activeDocId=t[t.length-1].id,M(),!0)}
                                                                                                                                                                                 }
                                                                                                                                                                                )}
                                                                                                                                                                 )}
                                function D(e,t){const a=t.docs||[],n=[...a].sort((e,t)=>(t.pinned?1:0)-(e.pinned?1:0));null==m.activeDocId&&a.length&&(m.activeDocId=n[0].id);const s=a.find(e=>e.id===m.activeDocId)||n[0];e.innerHTML=`<div class="docs-layout">\n<div class="doc-list">${n.map(e=>`<div class="doc-item ${s&&e.id===s.id?"active":""}
                                " data-id="${e.id}
                                "><span class="doc-pin ${e.pinned?"pinned":""}
                                " data-pin-id="${e.id}
                                " title="${e.pinned?"Unpin":"Pin to top"}
                                ">${e.pinned?"📌":"📍"}
                                </span>${d(e.title)}
                                <span class="cat">${d(e.cat)}
                                </span></div>`).join("")}
                                </div>\n<div class="doc-view">${s?`<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:10px;"><h2 style="margin:0;">${s.pinned?"📌 ":""}
                                ${d(s.title)}
                                </h2><button class="btn secondary small" id="btnEditDoc">Edit</button></div><div class="updated">Updated ${d(s.updated)}
                                 &middot; ${d(s.cat)}
                                 </div>${s.attachmentUrl?`<a class="doc-attachment" href="${s.attachmentUrl}
                                 " download="${d(s.attachmentName||"attachment")}
                                 ">📎 ${d(s.attachmentName||"Download attachment")}
                                 </a>`:""}
                                 <div class="doc-body">${d(s.body)}
                                 </div>`:'<div class="empty">No docs available</div>'}
                                 </div>\n</div>`,e.querySelectorAll(".doc-item").forEach(a=>{a.addEventListener("click",n=>{n.target.closest(".doc-pin")||(m.activeDocId=parseInt(a.dataset.id,10),D(e,t))}
                                                                                                                )}
                                                                                         ),e.querySelectorAll("[data-pin-id]").forEach(a=>{a.addEventListener("click",async n=>{n.stopPropagation();const s=parseInt(a.dataset.pinId,10),i=await S("toggleDocPinned",{id:s}
                                                                                                                                                                                                                                                   );i&&(m.data.docs=i,D(e,t))}
                                                                                                                                                              )}
                                                                                                                                       ),e.querySelector("#btnEditDoc")?.addEventListener("click",()=>{L({title:"Edit Doc",submitLabel:"Save",fields:[{key:"cat",label:"Category",type:"text",default:s.cat}
                                                                                                                                                                                                                                                      ,{key:"title",label:"Title",type:"text",default:s.title}
                                                                                                                                                                                                                                                      ,{key:"docBody",label:"Body",type:"textarea",default:s.body}
                                                                                                                                                                                                                                                      ,{key:"pinned",label:"Pin to top of Docs & Wiki (e.g. company policies)",type:"checkbox",default:s.pinned}
                                                                                                                                                                                                                                                      ,{key:"attachmentData",label:"Attachment (optional, 20MB max)",type:"file",default:s.attachmentName}
                                                                                                                                                                                                                                                      ],onSubmit:async e=>{if(!e.title||!e.docBody&&!e.attachmentData&&!s.attachmentUrl)return!1;const t=await S("editDoc",{id:s.id,cat:e.cat,title:e.title,docBody:e.docBody||"",pinned:e.pinned,attachmentData:e.attachmentData,attachmentName:e.attachmentDataName}
                                                                                                                                                                                                                                                                                                                                                                 );return!!t&&(m.data.docs=t,M(),!0)}
                                                                                                                                                                                                          }
                                                                                                                                                                                                         )}
                                                                                                                                                                                          )}
                                function A(e,t,a){const s=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],i=["Owner","Operations Manager","Growth & Marketing"].includes(p.role),l=["Owner","Operations Manager"].includes(p.role);function o(e){const t=String(e||"").trim().split(/\s+/);return t.length&&t[0]?((t[0][0]||"")+(t.length>1&&t[t.length-1][0]||"")).toUpperCase():"??"}
                                                  async function r(){if(m.staffList)return m.staffList;try{const e=await fetch("/api/users");if(!e.ok)return m.staffList=[],m.staffList;const t=await e.json();m.staffList=(t.data||[]).map(e=>e.name)}
                                                                     catch{m.staffList=[]}
                                                                     return m.staffList}
                                                  function c(e){const t=void 0;L({title:"Add Content Calendar Item",submitLabel:"Add",fields:[{key:"day",label:"Day",type:"select",default:e||"Mon",options:s.map(e=>({value:e,label:e}
                                                                                                                                                                                                                      ))}
                                                                                                                                              ,{key:"title",label:"Content title",type:"text"}
                                                                                                                                              ],onSubmit:async e=>{if(!e.title)return!1;const t=await S("addCalendarContent",e);return!!t&&(m.data.marketing_calendar=t,M(),!0)}
                                                                                 }
                                                                                 )}
                                                  function v(e){L({title:"Add Upcoming Event",submitLabel:"Add",fields:[{key:"name",label:"Event name",type:"text"}
                                                                                                                        ,{key:"when",label:"When (e.g. Wed, Jul 29)",type:"text",default:e||""}
                                                                                                                        ],onSubmit:async e=>{if(!e.name||!e.when)return!1;const t=await S("addCalendarEvent",e);return!!t&&(m.data.upcoming_events=t,M(),!0)}
                                                                  }
                                                                  )}
                                                  async function u(e){const t=s.map(e=>({value:e,label:e}
                                                                                        )),a=await r(),n=(m.data.shift_schedule||{}
                                                                                                          )[e||"Mon"];L({title:"Set Shift Coverage",submitLabel:"Save",wide:!0,fields:[{key:"day",label:"Day",type:"select",default:e||"Mon",options:t}
                                                                                                                                                                                       ,{key:"assignees",label:"Who's on shift",type:"multiselect",default:n?.assignees||[],options:a.map(e=>({value:e,label:e}
                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                       ,{key:"note",label:"Note (optional)",type:"text",default:n?.note||""}
                                                                                                                                                                                       ],onSubmit:async e=>{const t=await S("addShift",{day:e.day,assignees:e.assignees,note:e.note}
                                                                                                                                                                                                                            );return!!t&&(m.data.shift_schedule=t,M(),!0)}
                                                                                                                         }
                                                                                                                        )}
                                                  function h(e,t){let a=n.querySelector("#dayDetailOverlay");a||(a=document.createElement("div"),a.className="overlay",a.id="dayDetailOverlay",n.appendChild(a));const s=(m.data.marketing_calendar||{}
                                                                                                                                                                                                                          )[e]||[],r=(m.data.shift_schedule||{}
                                                                                                                                                                                                                                      )[e],p=(m.data.upcoming_events||[]).filter(t=>(t.when||"").split(",")[0].trim()===e),h=t?t.toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"}
                                                                                                                                                                                                                                                                                                                                                    ):e;a.innerHTML=`\n<div class="modal wide">\n<h3>${d(h)}
                                                                                                                                                                                                                                                                                                                                                    </h3>\n<div class="day-detail-section">\n<h4>Shift coverage ${l?"<button data-dd-add-shift>+ Assign</button>":""}
                                                                                                                                                                                                                                                                                                                                                    </h4>\n${r&&r.assignees&&r.assignees.length?`<div class="cal-shift-people">${r.assignees.map(e=>`<span class="assignee-chip"><span class="av">${d(o(e))}
                                                                                                                                                                                                                                                                                                                                                    </span>${d(e)}
                                                                                                                                                                                                                                                                                                                                                    </span>`).join("")}
                                                                                                                                                                                                                                                                                                                                                    </div>${r.note?`<div class="cal-shift-note" style="margin-top:6px;">${d(r.note)}
                                                                                                                                                                                                                                                                                                                                                    </div>`:""}
                                                                                                                                                                                                                                                                                                                                                    `:'<div class="empty" style="padding:10px;">No one scheduled</div>'}
                                                                                                                                                                                                                                                                                                                                                    \n</div>\n<div class="day-detail-section">\n<h4>Events ${i?"<button data-dd-add-event>+ Add</button>":""}
                                                                                                                                                                                                                                                                                                                                                    </h4>\n${p.length?p.map(e=>`<div class="cal-event">📌 ${d(e.name)}
                                                                                                                                                                                                                                                                                                                                                    </div>`).join(""):'<div class="empty" style="padding:10px;">No events</div>'}
                                                                                                                                                                                                                                                                                                                                                    \n</div>\n<div class="day-detail-section">\n<h4>Content ${i?"<button data-dd-add-content>+ Add</button>":""}
                                                                                                                                                                                                                                                                                                                                                    </h4>\n${s.length?s.map(e=>`<div class="cal-item">${d(e.title)}
                                                                                                                                                                                                                                                                                                                                                    ${e.automated?'<span class="cal-auto">Auto</span>':""}
                                                                                                                                                                                                                                                                                                                                                    </div>`).join(""):'<div class="empty" style="padding:10px;">No content scheduled</div>'}
                                                                                                                                                                                                                                                                                                                                                    \n</div>\n<div class="modal-actions">\n<button class="btn secondary" id="dayDetailClose">Close</button>\n</div>\n</div>\n`,a.classList.add("show"),a.querySelector("#dayDetailClose").addEventListener("click",()=>a.classList.remove("show")),a.querySelector("[data-dd-add-shift]")?.addEventListener("click",()=>u(e)),a.querySelector("[data-dd-add-event]")?.addEventListener("click",()=>v(e+", ")),a.querySelector("[data-dd-add-content]")?.addEventListener("click",()=>c(e))}
                                                  function y(e){const t=String(e||"").trim(),a=t.replace(/^[A-Za-z]+,?\s*/,""),n=new Date;let s=new Date(a+", "+n.getFullYear());return isNaN(s.getTime())&&(s=new Date(t)),isNaN(s.getTime())?null:s}
                                                  function g(){t.innerHTML=`\n${i?'<button class="btn secondary" id="btnAddContent" style="margin-right:6px;">+ Content</button><button class="btn secondary" id="btnAddEvent" style="margin-right:6px;">+ Event</button>':""}
                                                  \n${l?'<button class="btn" id="btnAddShift">+ Shift</button>':""}
                                                  \n`,n.querySelector("#btnAddContent")?.addEventListener("click",()=>c()),n.querySelector("#btnAddEvent")?.addEventListener("click",()=>v()),n.querySelector("#btnAddShift")?.addEventListener("click",()=>u())}
                                                  function f(){const t=a.marketing_calendar||{}
                                                    ,n=a.upcoming_events||[],i=a.shift_schedule||{}
                                                    ,l={}
                                                    ;n.forEach(e=>{const t=(e.when||"").split(",")[0].trim();(l[t]=l[t]||[]).push(e)}
                                                               );const r=s[((new Date).getDay()+6)%7];e.innerHTML=`\n<div class="cal-toolbar">\n<div class="cal-view-toggle">\n<button data-cal-view="week" class="active">Week</button>\n<button data-cal-view="month">Month</button>\n</div>\n</div>\n<div class="panel">\n<h3>Weekly calendar</h3>\n<p style="font-size:12.5px;color:var(--muted);margin-top:-6px;">Click a day to see full details and add coverage.</p>\n<div class="cal-grid">${s.map(e=>{const a=t[e]||[],n=i[e],s=l[e]||[];return`<div class="cal-col ${e===r?"today":""}
                                                               " data-day="${e}
                                                               ">\n<div class="cal-day">${e}
                                                               </div>\n${n&&n.assignees&&n.assignees.length?`<div class="cal-shift"><div class="cal-shift-people">${n.assignees.map(e=>`<span class="assignee-chip"><span class="av">${d(o(e))}
                                                               </span>${d(e)}
                                                               </span>`).join("")}
                                                               </div>${n.note?`<span class="cal-shift-note">${d(n.note)}
                                                               </span>`:""}
                                                               </div>`:""}
                                                               \n${s.map(e=>`<div class="cal-event">📌 ${d(e.name)}
                                                               </div>`).join("")}
                                                               \n${a.length?a.map(e=>`<div class="cal-item">${d(e.title)}
                                                               ${e.automated?'<span class="cal-auto">Auto</span>':""}
                                                               </div>`).join(""):s.length||n&&n.assignees&&n.assignees.length?"":'<div class="cal-empty">Nothing scheduled</div>'}
                                                               \n</div>`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).join("")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>\n</div>\n`,$(),e.querySelectorAll("[data-day]").forEach(e=>{e.addEventListener("click",()=>h(e.dataset.day,null))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )}
                                                  function b(){const t=a.marketing_calendar||{}
                                                    ,n=a.upcoming_events||[],i=a.shift_schedule||{}
                                                    ,l=m.calMonthAnchor,d=l.getFullYear(),o=l.getMonth(),r=new Date(d,o,1),c=(r.getDay()+6)%7,v=new Date(d,o,1-c),u=void 0,p=(new Date).toDateString(),g=[];for(let e=0;e<42;e++){const t=new Date(v.getFullYear(),v.getMonth(),v.getDate()+e);g.push(t)}
                                                               e.innerHTML=`\n<div class="cal-toolbar">\n<div class="cal-view-toggle">\n<button data-cal-view="week">Week</button>\n<button data-cal-view="month" class="active">Month</button>\n</div>\n<div class="cal-nav">\n<button id="calMonthPrev">&larr;</button>\n<b>${r.toLocaleDateString("en-US",{month:"long",year:"numeric"}
                                                                                                                                                                                                                                                                                                                                                     )}
                                                                                                                                                                                                                                                                                                                                                     </b>\n<button id="calMonthNext">&rarr;</button>\n</div>\n</div>\n<div class="panel">\n<div class="cal-month-grid">\n${s.map(e=>`<div class="cal-month-head">${e}
                                                                                                                                                                                                                                                                                                                                                     </div>`).join("")}
                                                                                                                                                                                                                                                                                                                                                     \n${g.map(e=>{const a=s[(e.getDay()+6)%7],l=e.getMonth()===o,d=e.toDateString()===p,r=t[a]||[],c=i[a],v=n.filter(t=>{const a=y(t.when);return a&&a.toDateString()===e.toDateString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),u=[];return r.length&&u.push('<span class="cal-dot content"></span>'),v.length&&u.push('<span class="cal-dot event"></span>'),c&&c.assignees&&c.assignees.length&&u.push('<span class="cal-dot shift"></span>'),`<div class="cal-month-cell ${l?"":"other-month"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ${d?"today":""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       " data-cell-day="${a}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       " data-cell-date="${e.toISOString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ">\n<div class="dnum">${e.getDate()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>\n<div class="cal-month-dots">${u.join("")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>\n</div>`}
                                                                                                                                                                                                                                                                                                                                                               ).join("")}
                                                                                                                                                                                                                                                                                                                                                               \n</div>\n</div>\n`,$(),e.querySelector("#calMonthPrev").addEventListener("click",()=>{m.calMonthAnchor=new Date(d,o-1,1),b()}
                                                                                                                                                                                                                                                                                                                                                                                                                                         ),e.querySelector("#calMonthNext").addEventListener("click",()=>{m.calMonthAnchor=new Date(d,o+1,1),b()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ),e.querySelectorAll("[data-cell-day]").forEach(e=>{e.addEventListener("click",()=>h(e.dataset.cellDay,new Date(e.dataset.cellDate)))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )}
                                                  function $(){e.querySelectorAll("[data-cal-view]").forEach(e=>{e.addEventListener("click",()=>{m.calMode=e.dataset.calView,w()}
                                                                                                                                    )}
                                                                                                             )}
                                                  function w(){g(),"month"===m.calMode?b():f()}
                                                  "month"!==m.calMode&&(m.calMode="week"),m.calMonthAnchor||(m.calMonthAnchor=new Date),w()}
                                function q(e){["Owner","Operations Manager","Inventory Manager","Logistics Manager"].includes(p.role)?(e.innerHTML='<button class="btn" id="btnAddLead">+ Add Lead</button>',n.querySelector("#btnAddLead").addEventListener("click",()=>{L({title:"New Buying Lead",submitLabel:"Add Lead",fields:[{key:"title",label:"Title",type:"text"}
                                                                                                                                                                                                                                                                                                                                    ,{key:"customer",label:"Customer",type:"text"}
                                                                                                                                                                                                                                                                                                                                    ,{key:"value",label:"Estimated value ($)",type:"number",default:0}
                                                                                                                                                                                                                                                                                                                                    ,{key:"closer",label:"Closer",type:"select",default:p.role,options:i.map(e=>({value:e,label:e}
                                                                                                                                                                                                                                                                                                                                                                                                                 ))}
                                                                                                                                                                                                                                                                                                                                    ],onSubmit:async e=>{if(!e.title)return!1;const t=await S("addBuyingLead",e);return!!t&&(m.data.buying_leads=t,M(),!0)}
                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                             )):e.innerHTML=""}
                                function I(e){["Owner","Operations Manager","Inventory Manager"].includes(p.role)?(e.innerHTML='<button class="btn" id="btnAddInv">+ Add Item</button>',n.querySelector("#btnAddInv").addEventListener("click",()=>{L({title:"New Inventory Item",submitLabel:"Add Item",fields:[{key:"title",label:"Title",type:"text"}
                                                                                                                                                                                                                                                                                                                 ,{key:"items",label:"Item count",type:"number",default:1}
                                                                                                                                                                                                                                                                                                                 ,{key:"source",label:"Source",type:"text"}
                                                                                                                                                                                                                                                                                                                 ],onSubmit:async e=>{if(!e.title)return!1;const t=await S("addInventoryItem",e);return!!t&&(m.data.inventory_items=t,M(),!0)}
                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                       )):e.innerHTML=""}
                                function N(){n.querySelectorAll("#buyBoardWrap .card").forEach(e=>{e.addEventListener("dragstart",t=>{e.classList.add("dragging"),t.dataTransfer.setData("text/plain",e.dataset.id)}
                                                                                                                      ),e.addEventListener("dragend",()=>e.classList.remove("dragging"))}
                                                                                               ),n.querySelectorAll("#buyBoardWrap .col-body").forEach(e=>{e.addEventListener("dragover",e=>e.preventDefault()),e.addEventListener("drop",async t=>{t.preventDefault();const a=parseInt(t.dataTransfer.getData("text/plain"),10),n=await S("moveBuyingLead",{id:a,stage:e.dataset.status}
                                                                                                                                                                                                                                                                                                                                           );n&&(m.data.buying_leads=n,M())}
                                                                                                                                                                                                                                   )}
                                                                                                                                                       )}
                                function O(){n.querySelectorAll("#invBoardWrap .card").forEach(e=>{e.addEventListener("dragstart",t=>{e.classList.add("dragging"),t.dataTransfer.setData("text/plain",e.dataset.id)}
                                                                                                                      ),e.addEventListener("dragend",()=>e.classList.remove("dragging"))}
                                                                                               ),n.querySelectorAll("#invBoardWrap .col-body").forEach(e=>{e.addEventListener("dragover",e=>e.preventDefault()),e.addEventListener("drop",async t=>{t.preventDefault();const a=parseInt(t.dataTransfer.getData("text/plain"),10),n=await S("moveInventoryItem",{id:a,stage:e.dataset.status}
                                                                                                                                                                                                                                                                                                                                           );n&&(m.data.inventory_items=n,M())}
                                                                                                                                                                                                                                   )}
                                                                                                                                                       )}
                                function P(e,t,a){t.innerHTML="";const s=a.online_orders||[],i=a.refunded_orders||[],l=a.shopify_summary?.unfulfilledOrderCount??s.length,r=i.reduce((e,t)=>e+t.amount,0);function c(){const e=(n.querySelector("#searchBox")?.value||"").toLowerCase();return s.filter(t=>!e||t.order.toLowerCase().includes(e)||(t.customer||"").toLowerCase().includes(e))}
                                                  function v(){const e=n.querySelector("#boardArea");if(!e)return;const t=c();e.innerHTML=`<table>\n<thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment status</th><th>Created</th></tr></thead>\n<tbody>${t.map(e=>`<tr><td>${d(e.order)}
                                                 </td><td>${d(e.customer||"Guest")}
                                                  </td><td>$${e.total.toFixed(2)}
                                                  </td><td><span class="status-pill ${o(e.financialStatus)}
                                                  ">${d(e.financialStatus)}
                                                  </span></td><td>${new Date(e.createdAt).toLocaleDateString()}
                                                  </td></tr>`).join("")||'<tr><td colspan="5" class="empty">No orders match</td></tr>'}
                                                  </tbody>\n</table>`}
                                                  e.innerHTML=`\n<p style="font-size:12.5px;color:var(--muted);margin:-4px 0 14px;">Real orders from Shopify still marked unfulfilled — paid orders only, most recent first. This is the complete current count (${l}
                                                  ), not a partial sample. Refunded orders are shown separately below, with the logged reason, instead of counting toward "unfulfilled."</p>\n<div class="toolbar">\n<input type="search" id="searchBox" placeholder="Search orders or customers...">\n<div class="spacer"></div>\n</div>\n<div id="boardArea" style="max-height:340px;overflow-y:auto;margin-bottom:20px;"></div>\n<div class="panel">\n<h3>Refunded Orders (last 30 days)</h3>\n<p style="font-size:12.5px;color:var(--muted);margin-top:-6px;">${i.length}
                                                   orders, $${r.toFixed(2)}
                                                    total refunded. "No reason logged" means the refund note was left blank in Shopify, not that one wasn't given.</p>\n<table>\n<thead><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Status</th><th>Reason</th><th>Date</th></tr></thead>\n<tbody>${i.map(e=>`<tr><td>${d(e.order)}
                                                    </td><td>${d(e.customer||"Guest")}
                                                    </td><td>$${e.amount.toFixed(2)}
                                                    </td><td><span class="status-pill ${o(e.status)}
                                                    ">${d(e.status)}
                                                    </span></td><td>${d(e.reason)}
                                                    </td><td>${new Date(e.createdAt).toLocaleDateString()}
                                                    </td></tr>`).join("")||'<tr><td colspan="6" class="empty">No refunds in this window</td></tr>'}
                                                    </tbody>\n</table>\n</div>\n`,n.querySelector("#searchBox").addEventListener("input",v),v()}

function qL(e){["Owner","Operations Manager","Inventory Manager","Logistics Manager"].includes(p.role)?(e.innerHTML='<button class="btn" id="btnAddLead">+ Add Lead</button>',n.querySelector("#btnAddLead").addEventListener("click",()=>{L({title:"New Merchandise Lot",submitLabel:"Add Lead",fields:[{key:"title",label:"Title",type:"text"},{key:"source",label:"Customer",type:"text"},{key:"itemCount",label:"Item count",type:"number",default:1},{key:"estValue",label:"Estimated value ($)",type:"number",default:0},{key:"purchasePrice",label:"Purchase price ($, if known)",type:"number",default:0},{key:"closer",label:"Closer",type:"select",default:p.role,options:i.map(e=>({value:e,label:e}))},{key:"notes",label:"Notes (optional)",type:"textarea"}],onSubmit:async e=>{if(!e.title)return!1;const t=await S("addMerchandiseLot",e);return!!t&&(m.data.merchandise_lots=t,M(),!0)}})})):e.innerHTML=""}
                                function IL(e){["Owner","Operations Manager","Inventory Manager"].includes(p.role)?(e.innerHTML='<button class="btn" id="btnAddInv">+ Add Item</button>',n.querySelector("#btnAddInv").addEventListener("click",()=>{L({title:"New Inventory Item",submitLabel:"Add Item",fields:[{key:"title",label:"Title",type:"text"},{key:"itemCount",label:"Item count",type:"number",default:1},{key:"source",label:"Source",type:"text"}],onSubmit:async e=>{if(!e.title)return!1;const t=await S("addMerchandiseLot",e);if(!t)return!1;const last=t[t.length-1];const t2=await S("moveMerchandiseLot",{id:last.id,stage:"Receiving"});return!!t2&&(m.data.merchandise_lots=t2,M(),!0)}})})):e.innerHTML=""}
                                function NL(){n.querySelectorAll("#buyBoardWrap .card").forEach(e=>{e.addEventListener("dragstart",t=>{e.classList.add("dragging"),t.dataTransfer.setData("text/plain",e.dataset.id)}),e.addEventListener("dragend",()=>e.classList.remove("dragging"))}),n.querySelectorAll("#buyBoardWrap .col-body").forEach(e=>{e.addEventListener("dragover",e=>e.preventDefault()),e.addEventListener("drop",async t=>{t.preventDefault();const a=parseInt(t.dataTransfer.getData("text/plain"),10),n=await S("moveMerchandiseLot",{id:a,stage:e.dataset.status});n&&(m.data.merchandise_lots=n,M())})}),n.querySelectorAll("#buyBoardWrap [data-advance-lot]").forEach(el=>{el.addEventListener("click",async ev=>{ev.stopPropagation();const id=parseInt(el.dataset.advanceLot,10),stage=el.dataset.nextStage;const r=await S("moveMerchandiseLot",{id,stage});r&&(m.data.merchandise_lots=r,M())})})}
                                function OL(){n.querySelectorAll("#invBoardWrap .card").forEach(e=>{e.addEventListener("dragstart",t=>{e.classList.add("dragging"),t.dataTransfer.setData("text/plain",e.dataset.id)}),e.addEventListener("dragend",()=>e.classList.remove("dragging"))}),n.querySelectorAll("#invBoardWrap .col-body").forEach(e=>{e.addEventListener("dragover",e=>e.preventDefault()),e.addEventListener("drop",async t=>{t.preventDefault();const a=parseInt(t.dataTransfer.getData("text/plain"),10),n=await S("moveMerchandiseLot",{id:a,stage:e.dataset.status});n&&(m.data.merchandise_lots=n,M())})})}
                                return{C,E,T,D,A,q,I,N,O,P,qL,IL,NL,OL}
                                ;}
